### PR TITLE
Upload SidewalkPedestrianModel

### PR DESCRIPTION
**Pull request by samankim**

### CODE REVIEW

**Comment by MaximeBouton** [comment]
@samankim  Looks good, 
Do you plan on adding a tutorial (e.g. a notebook) as well?

**Comment by samankim** [comment]
@MaximeBouton Yes - I'll add one for the sidewalk example I created.

**Comment by MaximeBouton** [comment]
You can also add some unit tests

**Comment by samankim** [comment]
I added a test and the tutorial for the sidewalk example.

**Pull request merged**
