### PR TITLE
docs to literate

### PR DESCRIPTION
**Pull request by mattuntergassmair**
Documentation tutorials from markdown format to Literate format (allows including and testing and conversion to markdown&notebooks)

### CODE REVIEW

**Comment by mattuntergassmair** [comment]
work in progress, needs a few more fixes (will take care of it tomorrow)

**Comment by MaximeBouton** [comment]
Something to be aware of, if we add AutoViz in the testing dependencies we will have a cycle!

**Comment by mattuntergassmair** [comment]
> Something to be aware of, if we add AutoViz in the testing dependencies we will have a cycle!

That's correct, but since it is an extra dependency that's used for tests only I wouldn't think that's a problem, right? The only alternatives are 1. not running the tutorials as part of the test suite or 2. not doing any visualization in the tutorials, but I guess none of those options is desireable.

Do you think it would be better (in this context, and in general), to have a separate `Project.toml` for `tests` (i.e. `tests/Project.toml` just like for `docs`) rather than having it in the `[extras]` section? I am a bit confused about the best practices with regards to this

**Comment by MaximeBouton** [comment]
There is quite a lot going on on `master` and `incorporate_rec`. I would say we finish the work there, and fix the tutorials here + merge after?

**Pull request merged**
