### PR TITLE
[WIP] Big Refactor

### PR DESCRIPTION
**Pull request by MaximeBouton**
# AutomotiveDrivingModels.jl Refactor

PR to refactor the structure of the package. Assign yourself to some tasks by editing this description.

For each new folder we should:
- import the relevant piece of code from the current repository
- open issues if you  notice something weird or inefficient and we will fix it at the second pass
- write tests
- write doc strings
- write a documentation page

New folder structure : `folder` (dependencies)
- [x] `Roadways`  (no deps): roadway definition, roadway generation, projections, frenet frame
  - [x] code moved
  - [x] test written
  - [x] doc written
- [x] `VehicleDefinitions` (no deps): abstract type, interface, current vehicle definitions - Raunak
  - [x] code moved
  - [x] test written
  - [x] doc written
  - Question: Should we change the name to reflect Samantha Kim's comment ref. pedestrians
    should not be called vehicles. Further, should we include `bicyclemodel` with `CAR`, `TRUCK` etc
    as opposed to being a standalone thing as it is now?
- [x] `States` (roadways, agent definitions): current states definition and scenes - Raunak
  - [x] code moved
  - [x] test written
  - [x] doc written
  - Question: What is the correct way to test constructors for example `VehicleState` and 
    associated `Base.show` and `Base.write` methods?
- [x] `CollisionCheckers` (states, agent definitions): collision checking utilities
  - [x] code moved
  - [x] test written
  - [x] doc written
- [x] `Actions` (roadway, states, agent definitions): interface, current action definitions 
  - [x] code moved 
  - [x] test written 
  - [x] doc written
- [ ] `FeatureExtraction`: current feature extraction tools, helpers function to get neighbors and lane info
  - [x] code moved
  - [x] test written
  - [ ] doc written
- [ ] `DriverModels` (roadway, states, actions, features): interface, current driver model
  - [x] code moved
  - [x] test written
  - [ ] doc written
- [x] `Simulation`: simulation , callbacks
  - [x] code moved
  - [x] test written
  - [x] doc written

After the first pass:
- [x] make sure the tutorials still runs
- [ ] we should tests other project on this branch of AutomotiveDrivingModels.jl,
since this is just a refactor nothing should break.

**Questions**

- Should we reexport `Vec`?
- Should we reexport `Records`?
  
**Notable changes**

A lot of files are unused, we should not include them in the refactor. If they might be useful in the short term, just open an issue. 
No 1d/2d splitting.
Rename filenames if it is relevant.

### CODE REVIEW

**Comment by raunakbh92** [comment]
I will work on `states`.

**Comment by raunakbh92** [comment]
I think we should not include `scenes` within `states`. Reason is that `scenes` is one level higher in the heirarchy as it relies on `state`, `vehicle_definition`, and `roadway`. So, I think `scenes` should be a separate folder of its own.

**Comment by MaximeBouton** [comment]
@raunakbh92 Could you take a look at the agent definition interface I just pushed ?

**Comment by MaximeBouton** [comment]
Let's merge 🎉

**Pull request merged**
